### ISSUE TITLE
fix the note cursor based pagination implementation

### ISSUE THREAD

**Issue by n1ru4l** [dungeon-revealer/dungeon-revealer#1010]
The current where condition for the notes cursor is incorrect. https://stackoverflow.com/questions/38017054/mysql-cursor-based-pagination-with-multiple-columns

**Comment by AlexLeporiday** [comment]
I'm looking at the query and the only issue I can see with it is that you're using creation date ordered by descending so that newer notes appear first. This means that while paging notes the newly created notes will never appear as you're always paging backwards in time.

Is there something else that I am missing?

**Comment by n1ru4l** [comment]
See the stack overflow thread, the where condition for the cursor should behave like a tuple comparison. Adding nee items will be added by the upcoming subscription list updater
