### ISSUE TITLE
Add images to tokens

### ISSUE THREAD

**Issue by apclary** [dungeon-revealer/dungeon-revealer#173]
Add the ability to set an image as the background of a token. For example, a goblin's face. Would need to automatically crop and resize the image to fit onto the token unless you wanted to make a more complex prompt for this purpose.

As a stretch goal, maybe include a standard set of free use images with the application - e.g. a sword/shield, a staff, a dagger, orcs and goblins, dragons, townsfolk, etc.

**Comment by n1ru4l** [comment]
@JosephSamela [wrote](https://github.com/dungeon-revealer/dungeon-revealer/issues/603):
>Today tokens are colors with text.
>
>![image](https://user-images.githubusercontent.com/16111451/87941131-a6149e00-ca68-11ea-98fc-0af70136c1fc.png)
>
>It would be fun to add graphics!
>
>![gobiln-token](https://user-images.githubusercontent.com/16111451/87941308-f4c23800-ca68-11ea-89c8-a9590487fc85.png)
>
>Thoughts?


@JosephSamela This is already heavily requested on our discord server 😅. With v1.10.0 we will have a complete re-write of the map view for the players. Up next we also want to refactor the dm view to use the same basis as the player view. Then after this is finished we can tackle this! I want to post-pone it until then because we would otherwise have to deal with two implementations (for the player and the dm view).
