### ISSUE TITLE
use renovate instead of depfu for pinning dependencies

### ISSUE THREAD

**Issue by n1ru4l** [dungeon-revealer/dungeon-revealer#196]
@apclary Overall renovate has a better DX then depfu:

- The config file is located inside repository (so I can do adjustments without bothering you to tweak the depfu configuration which is webinterface and repo-owner only)
- batches mono-repo updates (like react & react-dom)

Therefore I would recommend removing depfu and adding the renovate integration (which is free for Open Source). You can add renovate here: https://github.com/marketplace/renovate/plan/

Despite that, we could still move dungeon-revealer to a Github organization (which is free for Open Source) and would allow other contributors (like me) to do administration stuff.

**Comment by apclary** [comment]
Thanks, I've created an organization called dungeon-revealer and invited you to it. I also added renovate to this project (in the sense that I connected it to the repo, I made no code changes). 

I think an organization makes sense for the future, especially as you've taken such a lead on the development efforts and your specialization seems to be more in line with the front end with DR mostly entails. My concern is mainly that when people view my GitHub profile, I'd prefer they at least see a link to the organization prominently, if possible, rather than an old version of the code as my personal repository. Maybe that's not possible, and if not then I'm fine to migrate to an organization.

I imagine we'd want to migrate over the other contributions to this organization as well. I did not migrate the repo to the org either.

Let me know what you think or what specific actions you'd like me to take.

**Comment by n1ru4l** [comment]
> My concern is mainly that when people view my GitHub profile, I'd prefer they at least see a link to the organization prominently, if possible, rather than an old version of the code as my personal repository. Maybe that's not possible, and if not then I'm fine to migrate to an organization.

@apclary You can pin a project from an organization to your profile (Click Customize your pins, e.g. I pinned react-native-community/react-native-camera) and you can set your organization membership status to "public", so you have a shiny icon below your profile (check my profile: https://github.com/n1ru4l).

Instead of adding I new repo on the organization I would recommend moving this one over there, that way the old URL (https://github.com/apclary/dungeon-revealer) will automatically redirect to the new URL.


Furthermore, I did not receive an invitation invite 😐. Dunno whether this is an issue with Github, did not receive an email either.

**Comment by apclary** [comment]
OK, I think it's done now :) Let me know if you did not get the email again.

**Comment by thorgod** [comment]
Looks good, I still get emails and nothing changed besides the Org
https://github.com/dungeon-revealer/dungeon-revealer/

**Comment by apclary** [comment]
Are we good to close this?

**Comment by n1ru4l** [comment]
Yes!
