### ISSUE TITLE
Windows Crash 

### ISSUE THREAD

**Issue by thorgod** [dungeon-revealer/dungeon-revealer#202]
Mid game the back end crashed, I was in the middle of a session around 1 hours in when the backend crashed. I was not doing any thing strange just revealing areas and hitting send.

I will see if I can recreate the issue to figure the cause. (Its a bummer because I was mid game with the tool)

More information to come

**Comment by apclary** [comment]
Yes, possible to add some telemetry data to the application. I'll defer to @n1ru4l on best practices here, whether to spam log.trace() or just write data to a separate file.

**Comment by n1ru4l** [comment]
Sorry to hear that, I hope it didn’t have a huge impact. 

Application logs would be helpful. We could by default write all (error) logs to a file or use a service like sentry. Sentry would automatically collect all occurring errors.

**Comment by thorgod** [comment]
Able to re-create, hitting send a bunch of times over and over again, causes the failure.

@n1ru4l  Probably need to make a buffer or something async before writing to file again. 


Backend
```
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, open '\dungeon-revealer-1.4.0\dungeon-revealer-1.4.0\data\maps\dfe19483-569f-4581-b681-d4520d48ff1f\fog.live.png'
Emitted 'error' event on WriteStream instance at:
←[90m    at errorOrDestroy (internal/streams/destroy.js:107:12)←[39m
←[90m    at WriteStream.onerror (_stream_readable.js:758:7)←[39m
←[90m    at WriteStream.emit (events.js:210:5)←[39m
    at C:\Users\michael.leuer\Documents\dungeon-revealer-1.4.0\dungeon-revealer-1.4.0\node_modules\←[4mgraceful-fs←[24m\graceful-fs.js:293:14
    at C:\Users\michael.leuer\Documents\dungeon-revealer-1.4.0\dungeon-revealer-1.4.0\node_modules\←[4mgraceful-fs←[24m\graceful-fs.js:323:16
←[90m    at FSReqCallback.oncomplete (fs.js:157:23)←[39m {
  errno: ←[33m-4048←[39m,
  code: ←[32m'EPERM'←[39m,
  syscall: ←[32m'open'←[39m,
  path: ←[32m'dungeon-revealer-1.4.0\\dungeon-revealer-1.4.0\\data\\maps\\dfe19483-569f-4581-b681-d4520d48ff1f\\fog.live.png'←[39m
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by n1ru4l** [comment]
I will try to reproduce, ideally you could provide the map file 😇

**Comment by thorgod** [comment]
![SpiderDungeon_Original_Gridded](https://user-images.githubusercontent.com/13910170/66603035-2c0dcb00-eb60-11e9-99d7-2e5923dada44.jpg)

Here you go.

**Comment by n1ru4l** [comment]
@thorgod Thank you!

This could also happen with our JSON files (huge images, however, are more likely to be affected by those race conditions).

Multiple solutions for this problem:

Upload file to tmp file first, then unlink.

A queue, only do one file operation at a time, defer new requests until the queue is no longer blocked 🤔.

____

We could also think about a more performant way of storing the fog. PNG has an unnecessary high size. Maybe we can only send the draw instructions to the player in case we update the fog.

**Comment by thorgod** [comment]
@n1ru4l 

I think a quick solution is to disable the button until the process is finished writing to disc. 

Another idea is to have the files in server memory (Because writing to disk is costly), and only write on a save button. (Or write on a interval)

**Comment by thorgod** [comment]
@n1ru4l  I also thing PNG is not a good way to store FOG, if we kept it in a SVG or JSON it would be better; however, that would require a huge rework.

**Comment by n1ru4l** [comment]
Any idea on how to aggregate canvas draw statements? By using an event sourcing approach we would have redo functionality with ease + we would solve this problem. However, I have concerns, that such a solution could become slow. We would need an algorithm that over time aggregates old write statements.

**Comment by n1ru4l** [comment]
I thought a bit more and had the following idea:

**Hybrid event sourcing approach**

The backend consists of a service that stores the fog image in memory and applies modifications via incoming events (that the DM sends). The file is periodically persisted to the file system via debounce or throttle. This could be implemented with [node-canvas
](https://www.npmjs.com/package/canvas).

When the DM does an operation he sends an event encoded in JSON that describes the operation. The operation is then forwarded to the clients and the backend service that is responsible for persisting/distributing the image.

In case a new client (PC or even DM) connects he will request the initial fog state which is retrieved directly from the in-memory image representation ([node-canvas
](https://www.npmjs.com/package/canvas)). After he received that state all further updates to the fog will be applied on the client-side by receiving the JSON events.

In case we use [node-canvas
](https://www.npmjs.com/package/canvas) we would even have the benefit of having an identical write interface on the client and the server 🤔.

Instead of storing the fog as a PNG we could use a JPEG with only black-white (and interpret white as transparent on the client). The file size should become smaller that way

____
 
 The drawback of SVG IMHO is that there is no size limit, it can always get bigger. Dunno whether something like [SVGO](https://github.com/svg/svgo) could solve that issue.

**Comment by thorgod** [comment]
Looks interesting I took a quick look at node-canvas. I need to do some more research. Maybe a separate issue. 

I think a quick fix to the problem at hand would be best.  N There has to be a quick way of handling writing & reading to the same file in node-js, that acts like a buffer. I am sure this problem has many solutions already out there for node-js.

**Comment by n1ru4l** [comment]
Gonna try to do release a fix soon.

We can do the improvements later on in https://github.com/dungeon-revealer/dungeon-revealer/issues/202#issuecomment-544366059
