### ISSUE TITLE
websocket authorization

### ISSUE THREAD

**Issue by n1ru4l** [dungeon-revealer/dungeon-revealer#237]
Currently, there is no authorization for WebSocket operations.

**Comment by daball** [comment]
I noticed the package.json uses socket.io. If the WebSocket server is in fact socket.io, then here's a good place to start, though this only covers the case of authentication:
https://www.npmjs.com/package/socketio-auth

I've often considered this to be an interesting issue with which to contend. HTTP(S) has an authentication mechanism, though it is rarely ever used. Industry-wide, we usually use the combination of server-side sessions with client-side cookies in order to re-authenticate a session upon subsequent requests after the initial login.

But little thought is ever given to transferring the session to another protocol, application, or system. There are of course a variety of techniques. I recall from my university information security courses, Kerberos stands out as the strongest such technique for authorizing a subsequent system login access once authenticated against the domain/realm. This is definitely overkill: https://www.npmjs.com/package/kerberos

Nevermind the Kerberos ecosystem though. The technique is at the core of why it's effective. In this case, you could probably simply push the session cookie through the socket to the server and replay the session authentication to provide the same access to the session (server-side) cookie.

These again only regard authentication. Authorization techniques also vary, mostly based on need. RBAC, role-based access control, is probably the most common technique. This may be a good starting point: https://github.com/seeden/rbac

**Comment by n1ru4l** [comment]
Since the authorization is currently just a string that the admin defines for the admin and/or the player section a @simple sending the string with each socket message and comparing it on the server code" should be sufficient IMHO.

**Comment by n1ru4l** [comment]
@daball  https://github.com/dungeon-revealer/dungeon-revealer/pull/328 will fix this for now. In the future, if we require a more advanced authentication layer with different user types and more complex authentication/authorization strategies we can iterate based on the libraries you shared!
