### ISSUE TITLE
Zoomed map on the player view is blurry

### ISSUE THREAD

**Issue by GoOz** [dungeon-revealer/dungeon-revealer#450]
When given the same zoom, the map for the player view seem to be a much lower quality image than the DM view, even if everything runs locally on the same computer.

![blur](https://user-images.githubusercontent.com/1280069/82214386-09be0600-9916-11ea-8c64-e5c3e127ed21.gif)

DM view : Firefox 76
Player view : Chrome (79) (but same with Safari 13.1)

**Comment by n1ru4l** [comment]
On the player section, I limited the maximum resolution because it kept causing crashes on an iPad with Safari.

It might be smarter to just limit it for iOS Devices, based on the Browser Agent. I did test the behavior on any android device.

Since the DM Section does not "support" mobile safari (by design) there is no limit implemented there.

I currently do not have any other solution in mind other than reading the browser agent and set the maximum based on that.

@GoOz Could you share the dimensions of the loaded image in order to get a better feeling of what is enough and what is not?

The code related to determining the maximum resolution is determined here: https://github.com/dungeon-revealer/dungeon-revealer/blob/2eafd603bfbc9b477d4ec07a80dceefd9cfca596/src/player-area/player-area.js#L247-L252

The maximum is currently 3000 * 3000. The behaviour got changed as part of https://github.com/dungeon-revealer/dungeon-revealer/issues/130 in https://github.com/dungeon-revealer/dungeon-revealer/pull/223

**Comment by GoOz** [comment]
> Could you share the dimensions of the loaded image in order to get a better feeling of what is enough and what is not?

Sure thing! the one I used for the gif is **7704 × 9288**.

I do use DR on an ipad that I then display on a video projector, so I'm interested to know the actual limitation you will set in the end. If it's not too complicated maybe I can help you define when it crashes on iPad.

**Comment by n1ru4l** [comment]
you could actually test and tweak it. Just edit the file by changing the ` Math.min(window.innerWidth * 3, 3000)` and `Math.min(window.innerHeight * 3, 9000) ` values then run `npm run build` and start the server with `npm run start:server:dev`

**Comment by GoOz** [comment]
I set both to 9000 and I don't have any issue with my ipad :/ But it's quite recent (6th gen), maybe it breaks with older ones.

**Comment by n1ru4l** [comment]
@GoOz Then lets set it to 9000. I think it was most likely to related to the iOS/safari version than the power of the device. Do you think 9000 is enough for most maps?

**Comment by GoOz** [comment]
@n1ru4l Well, there's always a possibility to get bigger maps but I think It is indeed way enough for most dungeons. 
For example, I'm preparing the D&D campaign Dungeon of the Mad Mage which is a very big dungeon crawling campaign with more than 20 huge levels and the maps of those levels are around 8K pixels. And I insist, those are huuuuuuuge dungeons, so yeah I guess this is enough :)

**Comment by n1ru4l** [comment]
@GoOz Alright! I created https://github.com/dungeon-revealer/dungeon-revealer/pull/454

There is currently an issue with GitHub (The GitHub Actions are cancelled for some reason). After the issue is resolved I will merge the issue and publish v1.7.3 😊

Thank you for your input!

**Comment by maxb2** [comment]
Actions are working again. I just restarted all our failed builds.
