### ISSUE TITLE
If DM_PASSWORD ends in a "#" (or is more than 15 characters?) you're gonna have a bad time

### ISSUE THREAD

**Issue by shanel** [dungeon-revealer/dungeon-revealer#517]
I had a 16 character password with # as the last character and the dm's side, at least for map stuff was broken. I could upload maps but the thumbmnail would be broken and if followed lead to a {"data":null,"error":{"message":"Unauthenticated Access","code":"ERR_UNAUTHENTICATED_ACCESS"}}

If the map was loaded it would go to the editing view but it would be all white and there would be nothing to edit.

Uploaded media and the notes functionality seemed to be fine.

I also noted the window would reload periodically if I left it in that state.

On a hunch I removed the "#" from the password (which I can see is getting passed around in the url) and everything started working just fine.

I am assuming there is an issue with url escaping?

**Comment by n1ru4l** [comment]
https://github.com/n1ru4l/dungeon-revealer/blob/c059e10637cc9a909d46c23c1bb5997a5c42ff26/src/player-area/player-area.js#L147

The hash character causing troubles makes a lot of sense since we are not encoding the password which is passed as a query parameter for images.

It should be encoded/decoded.
